const WorkoutsActionTypes = {
    GET_WORKOUTS_START: 'GET_WORKOUTS_START',
    GET_WORKOUTS_SUCCESS: 'GET_WORKOUTS_SUCCESS',
    GET_WORKOUTS_FAILURE: 'GET_WORKOUTS_FAILURE',
    POST_WORKOUTS_START: 'POST_WORKOUTS_START',
    POST_WORKOUTS_SUCCESS: 'POST_WORKOUTS_SUCCESS',
    POST_WORKOUTS_FAILURE: 'POST_WORKOUTS_FAILURE',
};

export default WorkoutsActionTypes;