
const WorkoutsActionTypes = {
    GET_WORKOUTS_SUCCESS: 'GET_WORKOUTS_SUCCESS',
    GET_WORKOUT_SUCCESS: 'GET_WORKOUT_SUCCESS',
    POST_WORKOUTS_SUCCESS: 'POST_WORKOUTS_SUCCESS',
    WORKOUTS_FAILURE: 'WORKOUTS_FAILURE'
};

export default WorkoutsActionTypes;