const ProfileActionTypes = {
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
    CLEAR_PROFILE_SUCCESS: 'CLEAR_PROFILE_SUCCESS'
};

export default ProfileActionTypes;