const ProfileActionTypes = {
    GET_PROFILE_START: 'GET_PROFILE_START',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE'
};

export default ProfileActionTypes;